all: 1.3.c 1.4.c 1.5.c 1.6.c 1.7.c ../apue.c 
	gcc 1.3.c ../apue.c -I ../ -o 1.3.out
	gcc 1.4.c ../apue.c -I ../ -o 1.4.out
	gcc 1.5.c ../apue.c -I ../ -o 1.5.out
	gcc 1.6.c ../apue.c -I ../ -o 1.6.out
	gcc 1.7.c ../apue.c -I ../ -o 1.7.out
clean:
	rm -rf *.out
